### ISSUE TITLE
asp core 5.0 update

### ISSUE THREAD

**Issue by weedkiller** [zdy1988/Zdy.Metronic.TagHelpers#1]
Hi can you please update, this is wonderful. I have the theme... and could use this

**Comment by zdy1988** [comment]
Sorry, my brother !

I don't have time to do this. I'm very busy, but this project is very simple. You can incorporate the code into your project. I think it should be very simple to modify it...

**Comment by weedkiller** [comment]
ok thanks. Is it just pasting the new files in the CSS, can you please give me a brief idea on what steps I would follow..
